Repository fine-ants/FineAnts-was, pull requests merged in 2023-12, with the labels that each got.

#47 [feat] 포트폴리오 상세 조회 및 종목 조회시 SSE 로직 변경
  src/main/java/codesquad/fineants/domain/stock_dividend/StockDividend.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  src/test/java/codesquad/fineants/spring/api/kis/KisServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: feat

#50 [fix] 테스트 코드 모킹 설정 변경
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
Labels: bug

#56 [fix] calculate current year dividend
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: bug

#51 [feat] 일반 회원가입, 로그인 기능 구현
  build.gradle
  src/main/java/codesquad/fineants/domain/member/MemberRepository.java
  src/main/java/codesquad/fineants/spring/api/S3/service/AmazonS3Service.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/LoginRequest.java
  src/main/java/codesquad/fineants/spring/api/member/request/SignUpRequest.java
  src/main/java/codesquad/fineants/spring/api/member/request/VerifyEmailRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/LoginResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/member/service/OauthMemberRedisService.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/main/java/codesquad/fineants/spring/config/AwsS3Config.java
  src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
Labels: feat

#53 [feat] 포트폴리오 차트 조회 API 구현
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/domain/stock_dividend/StockDividend.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/DividendChart.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PieChart.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/SectorChart.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioChartResponse.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDividendChartItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioPieChartItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioSectorChartItem.java
  src/main/java/codesquad/fineants/spring/api/success/code/PortfolioStockSuccessCode.java
  src/main/java/codesquad/fineants/spring/config/JacksonConfig.java
  src/main/resources/application.yml
  src/main/resources/db/mysql/data.sql
  src/main/resources/db/mysql/init-schema.sql
  src/main/resources/sectors_kosdaq.tsv
  src/main/resources/sectors_kospi.tsv
  src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  src/test/java/codesquad/fineants/spring/api/kis/KisServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: feat

#61 [feat] delete portfolios
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingRepository.java
  src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryRepository.java
  src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfoliosDeleteRequest.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryCreateRequest.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/request/PurchaseHistoryModifyRequest.java
  src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  src/test/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: feat

#60 [feat] 포트폴리오 목록 조회 변경
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
Labels: feat

#67 [feat] 포트폴리오 상세 조회 및 종목 조회 API 분리
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/chart/DividendChart.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/chart/PieChart.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/chart/SectorChart.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/factory/PortfolioDetailFactory.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/factory/PortfolioHoldingDetailFactory.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailRealTimeItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingRealTimeItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingsRealTimeResponse.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingsResponse.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: feat

#71 [fix] sse 응답 메시지 이름 변경
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
Labels: feat

#72 [feat] 사용자 권한 검증 구현
  src/main/java/codesquad/fineants/domain/member/Member.java
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestController.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  src/main/java/codesquad/fineants/spring/auth/HasPortfolioAuthorization.java
  src/main/java/codesquad/fineants/spring/auth/HasPortfolioAuthorizationAspect.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: feat

#75 [fix] add default constructor
  src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfoliosDeleteRequest.java
Labels: bug

#78 [feat] 대시보드 구현
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistory.java
  src/main/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepository.java
  src/main/java/codesquad/fineants/spring/api/dashboard/controller/DashboardRestController.java
  src/main/java/codesquad/fineants/spring/api/dashboard/response/DashboardLineChartResponse.java
  src/main/java/codesquad/fineants/spring/api/dashboard/response/DashboardPieChartResponse.java
  src/main/java/codesquad/fineants/spring/api/dashboard/response/OverviewResponse.java
  src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
  src/main/java/codesquad/fineants/spring/api/success/code/DashboardSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/dashboard/DashboardServiceTest.java
Labels: feat

#80 [feat] 비밀번호 암호화, 프로필 사진 수정
  build.gradle
  src/main/java/codesquad/fineants/domain/member/Member.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/config/EncoderConfig.java
Labels: feat

#86 [bug] 라인 차트 조회시 데이터 정렬
  src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
Labels: bug

#82 [refactor] Oauth 소셜 로그인 리팩토링
  src/main/java/codesquad/fineants/domain/jwt/Jwt.java
  src/main/java/codesquad/fineants/domain/jwt/JwtProvider.java
  src/main/java/codesquad/fineants/domain/oauth/client/OauthClient.java
  src/main/java/codesquad/fineants/domain/oauth/client/google/GoogleOauthClient.java
  src/main/java/codesquad/fineants/domain/oauth/client/kakao/KakaoOauthClient.java
  src/main/java/codesquad/fineants/domain/oauth/client/naver/NaverOauthClient.java
  src/main/java/codesquad/fineants/domain/oauth/decoder/GoogleIDTokenDecoder.java
  src/main/java/codesquad/fineants/domain/oauth/decoder/IDTokenDecoder.java
  src/main/java/codesquad/fineants/domain/oauth/decoder/KakaoIDTokenDecoder.java
  src/main/java/codesquad/fineants/domain/oauth/properties/OauthProperties.java
  src/main/java/codesquad/fineants/domain/oauth/repository/InMemoryOauthClientRepository.java
  src/main/java/codesquad/fineants/domain/oauth/repository/OauthClientRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/JwkErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/manager/AuthorizationRequestManager.java
  src/main/java/codesquad/fineants/spring/api/member/request/AuthorizationRequest.java
  src/main/java/codesquad/fineants/spring/api/member/request/OauthMemberLoginRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/OauthMemberLoginResponse.java
  src/main/java/codesquad/fineants/spring/api/member/response/OauthSaveUrlResponse.java
  src/main/java/codesquad/fineants/spring/api/member/response/OauthToken.java
  src/main/java/codesquad/fineants/spring/api/member/response/OauthUserProfile.java
  src/main/java/codesquad/fineants/spring/api/member/response/OauthUserProfileResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberFactory.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/member/service/NicknameGenerator.java
  src/main/java/codesquad/fineants/spring/config/OauthConfig.java
  src/main/resources/application.yml
  src/main/resources/member.yml
  src/test/java/codesquad/fineants/domain/oauth/client/OauthClientTest.java
  src/test/java/codesquad/fineants/domain/oauth/decoder/KakaoIDTokenDecoderTest.java
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/AuthorizationRequestManagerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
Labels: refactor

#89 [docs] workflow 설정 변경
  .github/workflows/cicd.yml
  appspec.yml
  scripts/deploy.sh
  scripts/start.sh
Labels: documentation

#87 [feat] watchlist create, watchstock create, watchlist delete
  src/main/java/codesquad/fineants/domain/watch_list/WatchList.java
  src/main/java/codesquad/fineants/domain/watch_stock/WatchStock.java
  src/main/java/codesquad/fineants/domain/watch_stock/WatchStockRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/WatchListErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/success/code/WatchListSuccessCode.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
  src/main/java/codesquad/fineants/spring/api/watch_list/request/CreateWatchListRequest.java
  src/main/java/codesquad/fineants/spring/api/watch_list/request/CreateWatchStockRequest.java
  src/main/java/codesquad/fineants/spring/api/watch_list/response/CreateWatchListResponse.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
Labels: feat

#91 [fix] 종가 및 액세스 토큰 만료 문제 해결
  redis.conf
  src/main/java/codesquad/fineants/spring/api/kis/KisRedisService.java
  src/main/java/codesquad/fineants/spring/api/kis/KisService.java
  src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  src/main/java/codesquad/fineants/spring/api/kis/client/KisClient.java
  src/main/java/codesquad/fineants/spring/api/kis/manager/KisAccessTokenManager.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/PortfolioEvent.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/PortfolioEventListener.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/PortfolioEventPublisher.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/manager/SseEmitterManager.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/StockMarketChecker.java
  src/test/java/codesquad/fineants/spring/api/kis/KisRedisServiceTest.java
  src/test/java/codesquad/fineants/spring/api/kis/KisServiceTest.java
  src/test/java/codesquad/fineants/spring/api/kis/manager/KisAccessTokenManagerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioEventPublisherTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: bug

#95 [docs] CloudWatch 정보 추가
  docker-compose-dev.yml
Labels: documentation

#99 [fix] 포트폴리오 상세 조회시 currentValuation 프로퍼티 추가
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
Labels: bug
