Repository fine-ants/FineAnts-was, pull requests merged in 2024-02, with the labels that each got.

#179 #179 fix: ssl 재발급
  src/main/resources/ssl/keystore.p12
  src/main/resources/stocks.tsv
Labels: feat

#180 [feat] 프로필 정보 조회
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/response/ProfileResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
Labels: feat

#183 [feat] notification entity
  src/main/java/codesquad/fineants/domain/fcm_token/FcmToken.java
  src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPrice.java
  src/main/resources/db/mysql/init-schema.sql
Labels: feat

#194 [feat] 회원 알림 목록 조회
  src/main/java/codesquad/fineants/domain/BaseEntity.java
  src/main/java/codesquad/fineants/domain/notification/Notification.java
  src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/member/response/MemberNotification.java
  src/main/java/codesquad/fineants/spring/api/member/response/MemberNotificationResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationService.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
Labels: feat

#197 [feat] 회원 알림 관련 API 구현
  src/main/java/codesquad/fineants/domain/notification/Notification.java
  src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/NotificationErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationAllDeleteRequest.java
  src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationAllReadRequest.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationService.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/main/resources/db/mysql/init-schema.sql
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
Labels: feat

#198 [feat] 회원 알림 설정 수정 API 구현
  src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java
  src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java
  src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreferenceRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/NotificationPreferenceErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationPreferenceRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/MemberNotificationPreferenceResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceService.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/main/resources/db/mysql/data.sql
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceServiceTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
Labels: feat

#202 [fix] 알림 설정 수정 API 문제 해결
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceService.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceServiceTest.java
Labels: bug

#204 [feat] 회원 알림 권한 검사 AOP 추가
  src/main/java/codesquad/fineants/domain/oauth/support/AuthMember.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
  src/main/java/codesquad/fineants/spring/auth/HasNotificationAuthorization.java
  src/main/java/codesquad/fineants/spring/auth/HasNotificationAuthorizationAspect.java
Labels: bug, feat

#205 [fix] 알림 모두 읽음 API에 권한 검사 AOP 추가
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
Labels: bug

#206 [feat] 알림 메시지 발송 API 구현
  src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationSendRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/MemberNotificationSendResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationService.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
Labels: feat

#207 [fix] 오타 수정
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestController.java
Labels: bug

#209 [fix] FcmToken 테이블 생성 쿼리 오타 수정
  src/main/resources/db/mysql/init-schema.sql
Labels: bug

#211 [Refactor] 포트폴리오 종목 조회 리팩토링
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockService.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
Labels: refactor, performance

#212 [feat] 종목 지정가 알림 추가
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
  src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationCreateRequest.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationCreateResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
Labels: feat

#214 [feat] 종목 지정가 알림 제거 API 구현
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPrice.java
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
  src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationDeleteRequest.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationDeleteResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
Labels: feat

#215 [fix] 회원 알림 API의 payload 변경
  src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationSendRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/MemberNotification.java
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
Labels: feat

#219 [fix] 대시보드 오버뷰 리스폰스 바디에 totalGain 추가
  src/main/java/codesquad/fineants/spring/api/dashboard/response/OverviewResponse.java
  src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
Labels: bug

#221 [feat] 회원 종목 알림가 단일 제거 및 전체 제거 구현
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPrice.java
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
  src/main/java/codesquad/fineants/domain/target_price_notification/TargetPriceNotification.java
  src/main/java/codesquad/fineants/domain/target_price_notification/TargetPriceNotificationRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
  src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationCreateRequest.java
  src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationSingleDeleteRequest.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceItem.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationCreateResponse.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationSearchItem.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationSearchResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
Labels: feat

#222 [fix] 회원 알람 설정 수정 스펙 변경
  src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java
  src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java
  src/main/java/codesquad/fineants/spring/api/fcm/response/FcmDeleteResponse.java
  src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java
  src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationPreferenceRequest.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceService.java
  src/main/resources/db/mysql/init-schema.sql
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceServiceTest.java
Labels: feat

#224 [feat] FCM 토큰 등록 로직 변경
  src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java
  src/main/java/codesquad/fineants/domain/fcm_token/FcmToken.java
  src/main/java/codesquad/fineants/spring/api/fcm/response/FcmRegisterResponse.java
  src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java
  src/test/java/codesquad/fineants/spring/api/fcm/service/FcmServiceTest.java
Labels: feat

#226 [fix] 검증문 제거
  src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java
Labels: bug

#228 [feat] 종목 지정가 알림 목록 조회 API 구현
  docker-compose.yml
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationSearchItem.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
Labels: feat

#229 [feat] 종목 지정가 알림 정보 수정 API 구현
  .gitignore
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPrice.java
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
  src/main/java/codesquad/fineants/spring/api/stock/request/TargetPriceNotificationUpdateRequest.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationUpdateResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
Labels: feat

#230 [feat] 포트폴리오 활성 알림 목록 조회 API 구현
  src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioNotificationSettingSearchItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfolioNotificationSettingSearchResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/PortfolioSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortfolioNotificationSettingServiceTest.java
Labels: feat

#231 [docs] ci 수행시 test 추가
  .github/workflows/cicd.yml
Labels: documentation

#237 [docs] Spring Rest Docs 환경 추가
  build.gradle
  src/docs/asciidoc/api/stock_target_price.adoc
  src/docs/asciidoc/index.adoc
  src/main/resources/static/app.js
  src/main/resources/static/index.html
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/docs/RestDocsSupport.java
  src/test/java/codesquad/fineants/spring/docs/stock/stock_target_price/StockTargetPriceNotificationRestControllerDocsTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: documentation

#239 [feat] 종목 지정가 알림 특정 조회 API 구현
  src/docs/asciidoc/api/fcm.adoc
  src/docs/asciidoc/api/stock_target_price.adoc
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationSpecificItem.java
  src/main/java/codesquad/fineants/spring/api/stock/response/TargetPriceNotificationSpecifiedSearchResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  src/main/resources/stocks.tsv
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/docs/RestDocsSupport.java
  src/test/java/codesquad/fineants/spring/docs/stock/stock_target_price/StockTargetPriceNotificationRestControllerDocsTest.java
Labels: documentation, feat

#242 [fix] 프로필 조회 및 종목 지정가 알림 특정 조회 로직 수정
  src/main/java/codesquad/fineants/spring/api/member/response/ProfileResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationService.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationServiceTest.java
Labels: feat

#243 [feat] 매입 이력 이벤트에 따른 Push Notification 구현
  src/docs/asciidoc/api/notification.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java
  src/main/java/codesquad/fineants/domain/member/Member.java
  src/main/java/codesquad/fineants/domain/member/MemberRepository.java
  src/main/java/codesquad/fineants/domain/notification/Notification.java
  src/main/java/codesquad/fineants/domain/notification/PortfolioNotification.java
  src/main/java/codesquad/fineants/domain/notification/StockTargetPriceNotification.java
  src/main/java/codesquad/fineants/domain/notification/type/NotificationType.java
  src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  src/main/java/codesquad/fineants/domain/target_price_notification/TargetPriceNotification.java
  src/main/java/codesquad/fineants/spring/api/fcm/service/FcmService.java
  src/main/java/codesquad/fineants/spring/api/firebase/FirebaseMessagingService.java
  src/main/java/codesquad/fineants/spring/api/mail/MailService.java
  src/main/java/codesquad/fineants/spring/api/member/request/MemberNotificationSendRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/MemberNotification.java
  src/main/java/codesquad/fineants/spring/api/member/response/MemberNotificationSendResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/notification/controller/NotificationRestController.java
  src/main/java/codesquad/fineants/spring/api/notification/request/NotificationCreateRequest.java
  src/main/java/codesquad/fineants/spring/api/notification/response/NotificationCreateResponse.java
  src/main/java/codesquad/fineants/spring/api/notification/response/NotifyPortfolioMessageItem.java
  src/main/java/codesquad/fineants/spring/api/notification/response/NotifyPortfolioMessagesResponse.java
  src/main/java/codesquad/fineants/spring/api/notification/service/NotificationService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestController.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/event/EventHoldingValue.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/event/NotificationEventListener.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/event/PublishEvent.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/event/PublishEventAspect.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/event/PushNotificationEvent.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/event/SendableParameter.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryCreateResponse.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryDeleteResponse.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/response/PurchaseHistoryModifyResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/NotificationSuccessCode.java
  src/main/resources/db/mysql/data.sql
  src/test/java/codesquad/fineants/spring/api/firebase/FirebaseMessagingServiceTest.java
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
  src/test/java/codesquad/fineants/spring/api/notification/event/listener/NotificationEventListenerTest.java
  src/test/java/codesquad/fineants/spring/api/notification/service/NotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/MailServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
  src/test/java/codesquad/fineants/spring/api/stock/StockTargetPriceNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/auth/HasPortfolioAuthorizationAspectTest.java
  src/test/java/codesquad/fineants/spring/docs/notification/NotificationRestControllerDocsTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Labels: documentation, feat

#247 [fix] QA 버그 해결
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingRepository.java
  src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio/response/PortFolioItem.java
  src/main/java/codesquad/fineants/spring/api/portfolio/response/PortfoliosResponse.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/request/PortfolioStockCreateRequest.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockService.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
  src/test/java/codesquad/fineants/spring/docs/portfolio/PortfolioRestControllerDocsTest.java
Labels: bug

#248 [fix] qa 버그 문제 해결
  src/docs/asciidoc/api/dashboard.adoc
  src/docs/asciidoc/api/holding.adoc
  src/docs/asciidoc/api/member.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/codesquad/fineants/domain/fcm_token/FcmRepository.java
  src/main/java/codesquad/fineants/domain/notification/NotificationRepository.java
  src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreferenceRepository.java
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/stock_target_price/StockTargetPriceRepository.java
  src/main/java/codesquad/fineants/domain/target_price_notification/TargetPriceNotificationRepository.java
  src/main/java/codesquad/fineants/spring/api/dashboard/controller/DashboardRestController.java
  src/main/java/codesquad/fineants/spring/api/dashboard/response/OverviewResponse.java
  src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioHoldingDetailItem.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
  src/main/java/codesquad/fineants/spring/api/watch_list/event/WatchStockEvent.java
  src/main/java/codesquad/fineants/spring/api/watch_list/event/listener/WatchStockEventListener.java
  src/main/java/codesquad/fineants/spring/api/watch_list/event/publisher/WatchStockEventPublisher.java
  src/test/java/codesquad/fineants/spring/api/dashboard/service/DashboardServiceTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
  src/test/java/codesquad/fineants/spring/docs/RestDocsSupport.java
  src/test/java/codesquad/fineants/spring/docs/dashboard/DashboardRestControllerDocsTest.java
  src/test/java/codesquad/fineants/spring/docs/holding/PortfolioStockRestControllerDocsTest.java
  src/test/java/codesquad/fineants/spring/member/MemberRestControllerDocsTest.java
Labels: bug

#249 #244 fix: 포트폴리오의 예산이 0원인 경우 포트폴리오 차트 문제 해결
  src/main/java/codesquad/fineants/domain/notification_preference/NotificationPreference.java
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHolding.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberNotificationPreferenceServiceTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
Labels: bug
