Repository fine-ants/FineAnts-was, pull requests merged in 2024-01, with the labels that each got.

#108 [feat] 포트폴리오에 증권사 정보 검증 구현
  src/main/java/codesquad/fineants/domain/stock/Market.java
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/domain/stock/converter/MarketConverter.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/manager/PortfolioPropertiesManager.java
  src/main/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioProperties.java
  src/main/java/codesquad/fineants/spring/config/SpringConfig.java
  src/main/resources/application.yml
  src/main/resources/db/mysql/data.sql
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioPropertiesTest.java
Labels: feat

#107 [fix] 포트폴리오 상세 조회 응답 프로퍼티 변경
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/stock/Market.java
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/domain/stock/converter/MarketConverter.java
  src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/manager/PortfolioPropertiesManager.java
  src/main/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioProperties.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  src/main/java/codesquad/fineants/spring/config/SpringConfig.java
  src/main/resources/application.yml
  src/main/resources/db/mysql/data.sql
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioPropertiesTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: bug

#106 [fix] 포트폴리오 수정시 이름이 그대로인 경우 중복되는 문제 해결
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/stock/Market.java
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/domain/stock/converter/MarketConverter.java
  src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/manager/PortfolioPropertiesManager.java
  src/main/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioProperties.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  src/main/java/codesquad/fineants/spring/config/SpringConfig.java
  src/main/resources/application.yml
  src/main/resources/db/mysql/data.sql
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioPropertiesTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: bug

#104 [refactor] 종목 현재가 및 종가 갱신 스케줄링 메소드 개선
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/stock/Market.java
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/domain/stock/converter/MarketConverter.java
  src/main/java/codesquad/fineants/spring/api/dashboard/service/DashboardService.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/StockErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  src/main/java/codesquad/fineants/spring/api/kis/KisClientScheduler.java
  src/main/java/codesquad/fineants/spring/api/kis/KisMessageController.java
  src/main/java/codesquad/fineants/spring/api/kis/PortfolioSubscription.java
  src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  src/main/java/codesquad/fineants/spring/api/kis/interceptor/KisWebSocketInterceptor.java
  src/main/java/codesquad/fineants/spring/api/kis/listener/KisStompEventListener.java
  src/main/java/codesquad/fineants/spring/api/kis/manager/HolidayManager.java
  src/main/java/codesquad/fineants/spring/api/kis/manager/KisAccessTokenManager.java
  src/main/java/codesquad/fineants/spring/api/kis/manager/LastDayClosingPriceManager.java
  src/main/java/codesquad/fineants/spring/api/kis/manager/PortfolioSubscriptionManager.java
  src/main/java/codesquad/fineants/spring/api/kis/request/MessageData.java
  src/main/java/codesquad/fineants/spring/api/kis/service/KisRedisService.java
  src/main/java/codesquad/fineants/spring/api/kis/service/KisService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/manager/PortfolioPropertiesManager.java
  src/main/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioProperties.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/PortfolioHoldingEvent.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/listener/PortfolioEventListener.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/listener/PortfolioHoldingEventListener.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioEventPublisher.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioHoldingEventPublisher.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioDetailResponse.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/config/SpringConfig.java
  src/main/java/codesquad/fineants/spring/init/StartupApplicationListener.java
  src/main/resources/application.yml
  src/main/resources/db/mysql/data.sql
  src/main/resources/holidays.tsv
  src/test/java/codesquad/fineants/spring/api/kis/service/KisRedisServiceTest.java
  src/test/java/codesquad/fineants/spring/api/kis/service/KisServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/properties/PortfolioPropertiesTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioEventPublisherTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioStockServiceTest.java
Labels: refactor

#109 [feat] read watchlist
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/domain/watch_list/WatchList.java
  src/main/java/codesquad/fineants/domain/watch_list/WatchListRepository.java
  src/main/java/codesquad/fineants/domain/watch_stock/WatchStockRepository.java
  src/main/java/codesquad/fineants/spring/api/kis/manager/CurrentPriceManager.java
  src/main/java/codesquad/fineants/spring/api/success/code/WatchListSuccessCode.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
  src/main/java/codesquad/fineants/spring/api/watch_list/response/ReadWatchListResponse.java
  src/main/java/codesquad/fineants/spring/api/watch_list/response/ReadWatchListsResponse.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
Labels: feat

#111 [feat] 포트폴리오 종목 다수 삭제 API 구현
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioHoldingErrorCode.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/request/PortfolioStocksDeleteRequest.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/response/PortfolioStockDeletesResponse.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/api/success/code/PortfolioStockSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/PortfolioHoldingServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioEventPublisherTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
Labels: feat

#112 [fix] validate portfolio total investment
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/PortfolioErrorCode.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestController.java
  src/main/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryService.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: bug

#114 [fix] delete portfolioGainHisotry when deleting portfolio
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
Labels: bug

#115 [feat] 주식 종목 데이터 최신화
  src/main/java/codesquad/fineants/domain/portfolio_holding/PortfolioHoldingRepository.java
  src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistoryRepository.java
  src/main/java/codesquad/fineants/domain/stock/StockRepository.java
  src/main/java/codesquad/fineants/domain/stock_dividend/StockDividendRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/FileErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/service/WebClientWrapper.java
  src/main/java/codesquad/fineants/spring/api/stock/StockService.java
  src/main/java/codesquad/fineants/spring/api/stock/response/StockDataResponse.java
  src/main/java/codesquad/fineants/spring/util/StockFileUtil.java
  src/test/java/codesquad/fineants/domain/portfolio/PortfolioTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
Labels: feat

#117 [test] add market to stock entity
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
Labels: test

#119 [fix] get rid of watchlists in response
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
  src/main/java/codesquad/fineants/spring/api/watch_list/response/ReadWatchListsResponse.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
Labels: bug

#126 [fix] sse 문제 해결
  src/main/java/codesquad/fineants/domain/jwt/JwtProvider.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/JwtErrorCode.java
  src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  src/main/java/codesquad/fineants/spring/api/kis/service/KisService.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/PortfolioEvent.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/listener/PortfolioEventListener.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioEventPublisher.java
  src/main/java/codesquad/fineants/spring/filter/JwtAuthorizationFilter.java
  src/main/java/codesquad/fineants/spring/init/StartupApplicationListener.java
  src/main/resources/application.yml
  src/main/resources/stocks.tsv
Labels: bug

#134 [fix] 일반 로그인 오타 수정
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
Labels: bug

#135 [fix] Hikari Connection Pool 고갈 문제 해결
  src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  src/main/java/codesquad/fineants/spring/api/kis/service/KisService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioEventPublisher.java
  src/main/java/codesquad/fineants/spring/auth/HasPortfolioAuthorizationAspect.java
  src/main/resources/application.yml
  src/main/resources/stocks.tsv
  src/test/java/codesquad/fineants/domain/portfolio/PortfolioRepositoryTest.java
  src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioEventPublisherTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  src/test/java/codesquad/fineants/spring/auth/HasPortfolioAuthorizationAspectTest.java
Labels: bug

#132 [fix] 한국투자증권 액세스 토큰 만료시 발급 문제 해결
  src/main/java/codesquad/fineants/domain/portfolio/PortfolioRepository.java
  src/main/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspect.java
  src/main/java/codesquad/fineants/spring/api/kis/service/KisService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestController.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioEventPublisher.java
  src/main/java/codesquad/fineants/spring/auth/HasPortfolioAuthorizationAspect.java
  src/main/resources/application.yml
  src/main/resources/stocks.tsv
  src/test/java/codesquad/fineants/domain/portfolio/PortfolioRepositoryTest.java
  src/test/java/codesquad/fineants/domain/portfolio_gain_history/PortfolioGainHistoryRepositoryTest.java
  src/test/java/codesquad/fineants/spring/api/kis/aop/AccessTokenAspectTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/event/publisher/PortfolioEventPublisherTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryRestControllerTest.java
  src/test/java/codesquad/fineants/spring/auth/HasPortfolioAuthorizationAspectTest.java
Labels: bug

#128 [feat] add portfolio stock with purchase history
  build.gradle
  src/main/java/codesquad/fineants/domain/purchase_history/PurchaseHistory.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/PurchaseHistoryErrorCode.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/request/PortfolioStockCreateRequest.java
  src/main/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockService.java
  src/main/java/codesquad/fineants/spring/util/ObjectMapperUtil.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/controller/PortfolioStockRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
Labels: feat

#144 [fix] watchlist create
  src/main/java/codesquad/fineants/domain/watch_list/WatchList.java
  src/main/java/codesquad/fineants/domain/watch_stock/WatchStock.java
Labels: bug

#152 [feat] 포트폴리오 추가 및 수정시 입력정보 변경
  src/main/java/codesquad/fineants/domain/portfolio/Portfolio.java
  src/main/java/codesquad/fineants/spring/api/portfolio/PortFolioService.java
  src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioCreateRequest.java
  src/main/java/codesquad/fineants/spring/api/portfolio/request/PortfolioModifyRequest.java
  src/main/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationService.java
  src/main/java/codesquad/fineants/spring/api/portfolio_notification/manager/MailRedisManager.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio/PortFolioServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_notification/PortfolioNotificationServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_stock/service/PortfolioStockServiceTest.java
Labels: feat

#151 [feat] 계정 API, 프로필 정보 변경 API 구현
  src/main/java/codesquad/fineants/domain/member/Member.java
  src/main/java/codesquad/fineants/spring/api/S3/service/AmazonS3Service.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/ModifyPasswordRequest.java
  src/main/java/codesquad/fineants/spring/api/member/request/ProfileChangeRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/ProfileChangeResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
Labels: feat

#155 [fix] 회원 랜덤 닉네임 길이 변경
  src/main/resources/member.yml
  src/test/java/codesquad/fineants/spring/api/member/service/NicknameGeneratorTest.java
Labels: bug

#161 [fix] 계정 삭제 문제 해결
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
Labels: bug

#163 [fix] 비밀번호 변경 문제 해결
  src/main/java/codesquad/fineants/domain/member/MemberRepository.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
Labels: bug

#166 [fix] 회원 프로필 문제 해결
  src/main/java/codesquad/fineants/domain/member/Member.java
  src/main/java/codesquad/fineants/domain/member/MemberRepository.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/ProfileChangeRequest.java
  src/main/java/codesquad/fineants/spring/api/member/response/OauthMemberResponse.java
  src/main/java/codesquad/fineants/spring/api/member/response/ProfileChangeResponse.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/member/service/request/ProfileChangeServiceRequest.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/main/resources/application.yml
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
  src/test/resources/profile.jpeg
Labels: bug, refactor, test

#168 [refactor] 회원가입 서비스 리팩토링 및 테스트 코드
  src/main/java/codesquad/fineants/spring/api/S3/service/AmazonS3Service.java
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
  src/main/java/codesquad/fineants/spring/api/errors/handler/GlobalExceptionHandler.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/SignUpRequest.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/member/service/request/SignUpServiceRequest.java
  src/main/java/codesquad/fineants/spring/api/member/service/response/SignUpServiceResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
Labels: refactor, test

#169 [fix] 대시보드 서비스 클래스 테스트 코드 문제
  src/test/java/codesquad/fineants/spring/api/dashboard/DashboardServiceTest.java
  src/test/java/codesquad/fineants/spring/api/portfolio_gain_history/PortfolioGainHistoryServiceTest.java
  src/test/java/codesquad/fineants/spring/api/purchase_history/PurchaseHistoryServiceTest.java
Labels: bug, test

#170 [test] 회원가입 관련 서비스 테스트 코드 추가
  src/main/java/codesquad/fineants/spring/api/errors/errorcode/MemberErrorCode.java
  src/main/java/codesquad/fineants/spring/api/member/controller/MemberRestController.java
  src/main/java/codesquad/fineants/spring/api/member/request/VerifyCodeRequest.java
  src/main/java/codesquad/fineants/spring/api/member/request/VerifyEmailRequest.java
  src/main/java/codesquad/fineants/spring/api/member/service/MemberService.java
  src/main/java/codesquad/fineants/spring/api/member/service/OauthMemberRedisService.java
  src/main/java/codesquad/fineants/spring/api/member/service/VerifyCodeGenerator.java
  src/main/java/codesquad/fineants/spring/api/success/code/MemberSuccessCode.java
  src/main/resources/member.yml
  src/test/java/codesquad/fineants/spring/api/member/controller/MemberRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/member/service/MemberServiceTest.java
Labels: test

#171 [feat] change watchlist name
  src/main/java/codesquad/fineants/domain/watch_list/WatchList.java
  src/main/java/codesquad/fineants/domain/watch_list/WatchListRepository.java
  src/main/java/codesquad/fineants/spring/api/success/code/WatchListSuccessCode.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListService.java
  src/main/java/codesquad/fineants/spring/api/watch_list/request/ChangeWatchListNameRequest.java
  src/main/java/codesquad/fineants/spring/api/watch_list/response/WatchListHasStockResponse.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListServiceTest.java
Labels: feat

#174 [feat] stock detail
  src/main/java/codesquad/fineants/domain/stock/Stock.java
  src/main/java/codesquad/fineants/spring/api/stock/StockRestController.java
  src/main/java/codesquad/fineants/spring/api/stock/StockService.java
  src/main/java/codesquad/fineants/spring/api/stock/response/StockResponse.java
  src/main/java/codesquad/fineants/spring/api/success/code/StockSuccessCode.java
  src/test/java/codesquad/fineants/spring/api/stock/StockRestControllerTest.java
Labels: feat

#176 [fix] stockExists Endpoint
  src/main/java/codesquad/fineants/spring/api/watch_list/WatchListRestController.java
  src/test/java/codesquad/fineants/spring/api/watch_list/WatchListRestControllerTest.java
Labels: feat
